# Generated by Django 5.1.7 on 2025-03-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='cnt',
            field=models.IntegerField(default=0),
        ),
    ]
